project_id = "yhfcziouwodhjvukgjhr"

[functions.swiftbot-chat]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.whatsapp-service]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-campaign-worker]
verify_jwt = false
